FROM poetry_base    
# for python script to check if inside docker
ENV INSIDE_DOCKER yes  
# copy application: this is quite fast
COPY app/ /bose/app
CMD cd /bose && /root/.poetry/bin/poetry run python /bose/app/volume_ctrl.py
