FROM arm32v7/python:3.7-bullseye

# install poetry and then python deps using poetry: this takes ~15min
RUN apt-get install libxml2-dev libxslt-dev
RUN pip install --upgrade pip
COPY poetry.lock pyproject.toml poetry.toml /bose/
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
RUN cd /bose &&  /root/.poetry/bin/poetry install --no-root
